import React from "react";
import { WeekSummary } from "../types";

const DAY_LETTERS  = ["S", "T", "Q", "Q", "S", "S", "D"];
const DAY_PREFIXES = ["seg", "ter", "qua", "qui", "sex", "sáb", "dom"];

interface Props {
  summary: WeekSummary;
  /** Visual size in px (the square side). Defaults to 172. */
  size?: number;
}

/**
 * CSS replica of the badge used as a live preview inside the app.
 * The actual downloadable PNG is generated by generateWorkoutBadge() using Canvas API.
 */
export const WorkoutBadge: React.FC<Props> = ({ summary, size = 172 }) => {
  // Scale all sizes relative to the reference 172px
  const sc = size / 172;
  const px = (n: number) => `${Math.round(n * sc)}px`;

  return (
    <div
      style={{
        width: size,
        height: size,
        borderRadius: px(28),
        background: "rgba(5, 5, 13, 0.92)",
        border: "1.5px solid rgba(0,255,148,0.28)",
        boxShadow: "0 0 40px rgba(0,255,148,0.14), 0 0 0 1px rgba(255,255,255,0.04) inset",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        position: "relative",
        overflow: "hidden",
        flexShrink: 0,
        userSelect: "none",
      }}
    >
      {/* Top radial glow */}
      <div style={{
        position: "absolute", inset: 0, pointerEvents: "none",
        background: "radial-gradient(ellipse 80% 50% at 50% 0%, rgba(0,255,148,0.20) 0%, transparent 70%)",
      }} />

      {/* Brand */}
      <span style={{
        fontSize: px(8), fontWeight: 700, letterSpacing: "0.15em",
        color: "rgba(0,255,148,0.88)", marginTop: px(12), position: "relative",
      }}>
        ◆ SHAPE WARD ◆
      </span>

      {/* Separator */}
      <div style={{ width: "70%", height: 0.5, background: "rgba(0,255,148,0.11)", marginTop: px(5) }} />

      {/* Fire + streak */}
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", marginTop: px(7), gap: px(1), position: "relative" }}>
        <span style={{ fontSize: px(28), lineHeight: 1 }}>🔥</span>
        <span style={{ fontSize: px(40), fontWeight: 800, color: "#fff", lineHeight: 1.05, letterSpacing: "-0.02em" }}>
          {summary.streakWeeks}
        </span>
        <span style={{
          fontSize: px(6), fontWeight: 700, letterSpacing: "0.18em",
          color: "rgba(255,255,255,0.40)", textTransform: "uppercase",
        }}>
          Semanas seguidas
        </span>
      </div>

      {/* Separator */}
      <div style={{ width: "62%", height: 0.5, background: "rgba(255,255,255,0.07)", marginTop: px(7), marginBottom: px(7) }} />

      {/* Day dots */}
      <div style={{ display: "flex", gap: px(4), alignItems: "center", position: "relative" }}>
        {DAY_LETTERS.map((letter, i) => {
          const trained = summary.trainedDays.some(d => d.toLowerCase().startsWith(DAY_PREFIXES[i]));
          return (
            <div
              key={i}
              style={{
                width: px(16), height: px(16),
                borderRadius: "50%",
                background: trained ? "#00FF94" : "rgba(255,255,255,0.04)",
                border: trained ? "none" : "0.7px solid rgba(255,255,255,0.13)",
                boxShadow: trained ? "0 0 6px rgba(0,255,148,0.45)" : "none",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: px(6), fontWeight: 700,
                color: trained ? "#000" : "rgba(255,255,255,0.22)",
              }}
            >
              {letter}
            </div>
          );
        })}
      </div>

      {/* Week info */}
      <span style={{ fontSize: px(7), color: "rgba(255,255,255,0.24)", marginTop: px(7), position: "relative" }}>
        Semana {summary.weekNumber} · {summary.year}
      </span>

      {/* Watermark */}
      <span style={{
        fontSize: px(6), color: "rgba(0,255,148,0.20)",
        position: "absolute", bottom: px(8),
      }}>
        shape-ward.web.app
      </span>
    </div>
  );
};
