// Script to convert TACO CSV to TypeScript data file
// Run: node scripts/convert-taco.mjs

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CSV_PATH = 'C:/Users/Vilson/Downloads/taco-main/taco-main/formatados/alimentos.csv';
const OUT_PATH = path.join(__dirname, '../data/taco.ts');

function parseCSVLine(line) {
  const result = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === ',' && !inQuotes) {
      result.push(current);
      current = '';
    } else {
      current += ch;
    }
  }
  result.push(current);
  return result;
}

function toNum(val) {
  if (!val || val.trim() === 'NA' || val.trim() === '') return 0;
  const n = parseFloat(val.trim());
  if (isNaN(n) || n < 0.001) return 0;
  return Math.round(n * 10) / 10;
}

function normalizeText(text) {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[,.\-\/\\]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const raw = fs.readFileSync(CSV_PATH, 'utf-8');
const lines = raw.split('\n').filter(l => l.trim());

const foods = [];
for (let i = 1; i < lines.length; i++) {
  const cols = parseCSVLine(lines[i]);
  if (cols.length < 11) continue;

  const id = parseInt(cols[0], 10);
  const category = cols[1].trim();
  const name = cols[2].trim();
  const calories = toNum(cols[4]);
  const protein = toNum(cols[6]);
  const fat = toNum(cols[7]);
  const carbs = toNum(cols[9]);
  const fiber = toNum(cols[10]);

  if (!name || isNaN(id)) continue;

  foods.push({
    id,
    name,
    category,
    per100g: { calories, protein, carbs, fat, fiber },
    searchName: normalizeText(name),
  });
}

const ts = `// AUTO-GENERATED by scripts/convert-taco.mjs — DO NOT EDIT
// TACO - Tabela Brasileira de Composição de Alimentos (UNICAMP)
// ${foods.length} alimentos

export interface TacoFood {
  id: number;
  name: string;
  category: string;
  per100g: {
    calories: number;
    protein: number;
    carbs: number;
    fat: number;
    fiber: number;
  };
  searchName: string; // normalizado: sem acento, minúsculo
}

export const TACO_FOODS: TacoFood[] = ${JSON.stringify(foods, null, 2)};
`;

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, ts, 'utf-8');
console.log(`✓ Gerado: ${OUT_PATH} (${foods.length} alimentos)`);
